/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Insight {
  'title' : string,
  'description' : string,
  'metricName' : string,
  'severity' : Severity,
}
export interface InsightsResult { 'insights' : Array<Insight> }
export type MetricStatus = { 'warning' : null } |
  { 'good' : null } |
  { 'critical' : null };
export interface MetricValue {
  'status' : MetricStatus,
  'trend' : number,
  'value' : number,
  'unit' : string,
}
export interface MetricsResult {
  'leadTime' : MetricValue,
  'bugRate' : MetricValue,
  'cycleTime' : MetricValue,
  'prThroughputTrend' : number,
  'deploymentFrequency' : MetricValue,
  'prThroughputStatus' : MetricStatus,
  'prThroughput' : bigint,
}
export type Period = string;
export type Priority = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface Recommendation {
  'action' : string,
  'estimatedImpact' : string,
  'rationale' : string,
  'metricName' : string,
  'priority' : Priority,
}
export interface RecommendationsResult {
  'recommendations' : Array<Recommendation>,
}
export type Severity = { 'warning' : null } |
  { 'info' : null } |
  { 'critical' : null };
export interface _SERVICE {
  'getInsights' : ActorMethod<[Period], InsightsResult>,
  'getMetrics' : ActorMethod<[Period], MetricsResult>,
  'getRecommendations' : ActorMethod<[Period], RecommendationsResult>,
  'refreshData' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];