/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Period = IDL.Text;
export const Severity = IDL.Variant({
  'warning' : IDL.Null,
  'info' : IDL.Null,
  'critical' : IDL.Null,
});
export const Insight = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'metricName' : IDL.Text,
  'severity' : Severity,
});
export const InsightsResult = IDL.Record({ 'insights' : IDL.Vec(Insight) });
export const MetricStatus = IDL.Variant({
  'warning' : IDL.Null,
  'good' : IDL.Null,
  'critical' : IDL.Null,
});
export const MetricValue = IDL.Record({
  'status' : MetricStatus,
  'trend' : IDL.Float64,
  'value' : IDL.Float64,
  'unit' : IDL.Text,
});
export const MetricsResult = IDL.Record({
  'leadTime' : MetricValue,
  'bugRate' : MetricValue,
  'cycleTime' : MetricValue,
  'prThroughputTrend' : IDL.Float64,
  'deploymentFrequency' : MetricValue,
  'prThroughputStatus' : MetricStatus,
  'prThroughput' : IDL.Nat,
});
export const Priority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const Recommendation = IDL.Record({
  'action' : IDL.Text,
  'estimatedImpact' : IDL.Text,
  'rationale' : IDL.Text,
  'metricName' : IDL.Text,
  'priority' : Priority,
});
export const RecommendationsResult = IDL.Record({
  'recommendations' : IDL.Vec(Recommendation),
});

export const idlService = IDL.Service({
  'getInsights' : IDL.Func([Period], [InsightsResult], ['query']),
  'getMetrics' : IDL.Func([Period], [MetricsResult], ['query']),
  'getRecommendations' : IDL.Func([Period], [RecommendationsResult], ['query']),
  'refreshData' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Period = IDL.Text;
  const Severity = IDL.Variant({
    'warning' : IDL.Null,
    'info' : IDL.Null,
    'critical' : IDL.Null,
  });
  const Insight = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'metricName' : IDL.Text,
    'severity' : Severity,
  });
  const InsightsResult = IDL.Record({ 'insights' : IDL.Vec(Insight) });
  const MetricStatus = IDL.Variant({
    'warning' : IDL.Null,
    'good' : IDL.Null,
    'critical' : IDL.Null,
  });
  const MetricValue = IDL.Record({
    'status' : MetricStatus,
    'trend' : IDL.Float64,
    'value' : IDL.Float64,
    'unit' : IDL.Text,
  });
  const MetricsResult = IDL.Record({
    'leadTime' : MetricValue,
    'bugRate' : MetricValue,
    'cycleTime' : MetricValue,
    'prThroughputTrend' : IDL.Float64,
    'deploymentFrequency' : MetricValue,
    'prThroughputStatus' : MetricStatus,
    'prThroughput' : IDL.Nat,
  });
  const Priority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Recommendation = IDL.Record({
    'action' : IDL.Text,
    'estimatedImpact' : IDL.Text,
    'rationale' : IDL.Text,
    'metricName' : IDL.Text,
    'priority' : Priority,
  });
  const RecommendationsResult = IDL.Record({
    'recommendations' : IDL.Vec(Recommendation),
  });
  
  return IDL.Service({
    'getInsights' : IDL.Func([Period], [InsightsResult], ['query']),
    'getMetrics' : IDL.Func([Period], [MetricsResult], ['query']),
    'getRecommendations' : IDL.Func(
        [Period],
        [RecommendationsResult],
        ['query'],
      ),
    'refreshData' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };