/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Period = string;
export interface MetricsResult {
    leadTime: MetricValue;
    bugRate: MetricValue;
    cycleTime: MetricValue;
    prThroughputTrend: number;
    deploymentFrequency: MetricValue;
    prThroughputStatus: MetricStatus;
    prThroughput: bigint;
}
export interface Recommendation {
    action: string;
    estimatedImpact: string;
    rationale: string;
    metricName: string;
    priority: Priority;
}
export interface InsightsResult {
    insights: Array<Insight>;
}
export interface MetricValue {
    status: MetricStatus;
    trend: number;
    value: number;
    unit: string;
}
export interface Insight {
    title: string;
    description: string;
    metricName: string;
    severity: Severity;
}
export interface RecommendationsResult {
    recommendations: Array<Recommendation>;
}
export enum MetricStatus {
    warning = "warning",
    good = "good",
    critical = "critical"
}
export enum Priority {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum Severity {
    warning = "warning",
    info = "info",
    critical = "critical"
}
export interface backendInterface {
    getInsights(period: Period): Promise<InsightsResult>;
    getMetrics(period: Period): Promise<MetricsResult>;
    getRecommendations(period: Period): Promise<RecommendationsResult>;
    refreshData(): Promise<void>;
}
import type { Insight as _Insight, InsightsResult as _InsightsResult, MetricStatus as _MetricStatus, MetricValue as _MetricValue, MetricsResult as _MetricsResult, Priority as _Priority, Recommendation as _Recommendation, RecommendationsResult as _RecommendationsResult, Severity as _Severity } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getInsights(arg0: Period): Promise<InsightsResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getInsights(arg0);
                return from_candid_InsightsResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInsights(arg0);
            return from_candid_InsightsResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMetrics(arg0: Period): Promise<MetricsResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getMetrics(arg0);
                return from_candid_MetricsResult_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMetrics(arg0);
            return from_candid_MetricsResult_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecommendations(arg0: Period): Promise<RecommendationsResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecommendations(arg0);
                return from_candid_RecommendationsResult_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecommendations(arg0);
            return from_candid_RecommendationsResult_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async refreshData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.refreshData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.refreshData();
            return result;
        }
    }
}
function from_candid_Insight_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Insight): Insight {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_InsightsResult_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InsightsResult): InsightsResult {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_MetricStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MetricStatus): MetricStatus {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_MetricValue_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MetricValue): MetricValue {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_MetricsResult_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MetricsResult): MetricsResult {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Priority_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Priority): Priority {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Recommendation_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Recommendation): Recommendation {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_RecommendationsResult_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RecommendationsResult): RecommendationsResult {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Severity_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Severity): Severity {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _MetricStatus;
    trend: number;
    value: number;
    unit: string;
}): {
    status: MetricStatus;
    trend: number;
    value: number;
    unit: string;
} {
    return {
        status: from_candid_MetricStatus_n12(_uploadFile, _downloadFile, value.status),
        trend: value.trend,
        value: value.value,
        unit: value.unit
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    recommendations: Array<_Recommendation>;
}): {
    recommendations: Array<Recommendation>;
} {
    return {
        recommendations: from_candid_vec_n16(_uploadFile, _downloadFile, value.recommendations)
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    action: string;
    estimatedImpact: string;
    rationale: string;
    metricName: string;
    priority: _Priority;
}): {
    action: string;
    estimatedImpact: string;
    rationale: string;
    metricName: string;
    priority: Priority;
} {
    return {
        action: value.action,
        estimatedImpact: value.estimatedImpact,
        rationale: value.rationale,
        metricName: value.metricName,
        priority: from_candid_Priority_n19(_uploadFile, _downloadFile, value.priority)
    };
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    insights: Array<_Insight>;
}): {
    insights: Array<Insight>;
} {
    return {
        insights: from_candid_vec_n3(_uploadFile, _downloadFile, value.insights)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    description: string;
    metricName: string;
    severity: _Severity;
}): {
    title: string;
    description: string;
    metricName: string;
    severity: Severity;
} {
    return {
        title: value.title,
        description: value.description,
        metricName: value.metricName,
        severity: from_candid_Severity_n6(_uploadFile, _downloadFile, value.severity)
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    leadTime: _MetricValue;
    bugRate: _MetricValue;
    cycleTime: _MetricValue;
    prThroughputTrend: number;
    deploymentFrequency: _MetricValue;
    prThroughputStatus: _MetricStatus;
    prThroughput: bigint;
}): {
    leadTime: MetricValue;
    bugRate: MetricValue;
    cycleTime: MetricValue;
    prThroughputTrend: number;
    deploymentFrequency: MetricValue;
    prThroughputStatus: MetricStatus;
    prThroughput: bigint;
} {
    return {
        leadTime: from_candid_MetricValue_n10(_uploadFile, _downloadFile, value.leadTime),
        bugRate: from_candid_MetricValue_n10(_uploadFile, _downloadFile, value.bugRate),
        cycleTime: from_candid_MetricValue_n10(_uploadFile, _downloadFile, value.cycleTime),
        prThroughputTrend: value.prThroughputTrend,
        deploymentFrequency: from_candid_MetricValue_n10(_uploadFile, _downloadFile, value.deploymentFrequency),
        prThroughputStatus: from_candid_MetricStatus_n12(_uploadFile, _downloadFile, value.prThroughputStatus),
        prThroughput: value.prThroughput
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    warning: null;
} | {
    good: null;
} | {
    critical: null;
}): MetricStatus {
    return "warning" in value ? MetricStatus.warning : "good" in value ? MetricStatus.good : "critical" in value ? MetricStatus.critical : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): Priority {
    return "low" in value ? Priority.low : "high" in value ? Priority.high : "medium" in value ? Priority.medium : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    warning: null;
} | {
    info: null;
} | {
    critical: null;
}): Severity {
    return "warning" in value ? Severity.warning : "info" in value ? Severity.info : "critical" in value ? Severity.critical : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Recommendation>): Array<Recommendation> {
    return value.map((x)=>from_candid_Recommendation_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Insight>): Array<Insight> {
    return value.map((x)=>from_candid_Insight_n4(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
